

FORMA_PAGAMENTOS = {
    "1":"CRÉDITO EM CONTA CORRENTE NO ITAÚ",
    "02":"CHEQUE PAGAMENTO/ADMINISTRATIVO",
    "03":"DOC C",
    "05":"CRÉDITO EM CONTA POUPANÇA NO ITAÚ",
    "06":"CRÉDITO EM CONTA CORRENTE DE MESMA TITULARIDADE",
    "07":"DOC D",
    "10":"ORDEM DE PAGAMENTO À DISPOSIÇÃO",
    "13":"PAGAMENTO DE CONCESSIONÁRIAS",
    "16":"DARF NORMAL",
    "17":"GPS - GUIA DA PREVIDÊNCIA SOCIAL ",
    "18":"DARF SIMPLES",
    "19":"IPTU/ISS/OUTROS TRIBUTOS MUNICIPAIS",
    "22":"GARE - SP ICMS",
    "25":"IPVA",
    "27":"DPVAT",
    "30":"PAGAMENTO DE TÍTULOS EM COBRANÇA NO ITAÚ",
    "31":"PAGAMENTO DE TÍTULOS EM COBRANÇA EM OUTROS BANCOS",
    "32":"NOTA FISCAL - LIQUIDAÇÃO ELETRÔNICA",
    "35":"FGTS",
    "41":"TED - OUTRO TITULAR",
    "43":"TED - MESMO TITULAR",
    "45":"PIX TRANSFERÊNCIA ",
    "47":"PIX QR-CODE ",
    "60":"CARTÃO SALÁRIO",
    "91":"GNRE E TRIBUTOS COM CÓDIGO DE BARRAS"
}